export const data = {
    "en" : {
        "apartments":"Apartments",
        "about us":"About us",
        "sign in" : "Sign In",
        "sign up":"Sign Up",
        "address":'Address',
        "rooms":'Rooms',
        "baths":'Baths',
        "more details":'More Details',
        "sqft":'Sqft',
        "status":'Status',
        "price":'price',
        "both":"Sale / Rent",
        "rent":"Rent",
        "sale":"Sale",
        "minPrice":"Min Price",
        "maxPrice":"Max Price",
        "numRoom":"Number of rooms",
        "numBath" : "Number of baths",
        "city":"city",
        "search":"Search",
        "images":'Images',
        "details":"Details",
        "purchase":"Purchase"
    },
    "he":{
        "apartments":"דירות",
        "about us":"מי אנחנו",
        "sign in" : "התחבר",
        "sign up":"הרשמה",
        "address":'כתובת',
        "rooms":'חדרים',
        "baths":'מקלחות',
        "more details":'פרטים נוספים',
        "sqft":'שטח',
        "status":'מצב',
        "price":'מחיר',
        "both":"השכרה / מכירה",
        "rent":"השכרה",
        "sale":"מכירה",
        "minPrice":"מחיר החל מ",
        "maxPrice":"מחיר עד",
        "numRoom":"מספר חדרים",
        "numBath" : "מספר מקלחות",
        "city":"עיר",
        "search":"חיפוש",
        "images":'תמונות',
        "details":"פרטים",
        "purchase":"רכישה"
    }
};