export const data = {
    "en" : {
        "apartments":"Apartments",
        "about us":"About us",
        "sign in" : "Sign In",
        "sign up":"Sign Up",
        "address":'Address',
        "rooms":'Rooms',
        "baths":'Baths',
        "more details":'More Details',
        "sqft":'Sqft',
        "status":'Status',
        "price":'price',
        "both":"Sale / Rent",
        "rent":"Rent",
        "sale":"Sale",
        "minPrice":"Min Price",
        "maxPrice":"Max Price",
        "numRoom":"Number of rooms",
        "numBath" : "Number of baths",
        "city":"City",
        "search":"Search",
        "images":'Images',
        "details":"Details",
        "purchase":"Purchase",
        "found" : "Found",
        "advancedSearch":"Advanced Search",
        "location":"Location",
        "cancel":"Cancel",
        "type" : "Type",
        "uploadDate":"Upload Date",
        "house":"House",
        "ranch":"Ranch",
        "condo":"Condo",
        "land":"land",
        "all":"All",
        "agentDetails" : "Agent Details",
        "name" : "Name",
        "email": " E-mail",
        "phone" : "Phone"
    },
    "he":{
        "apartments":"דירות",
        "about us":"מי אנחנו",
        "sign in" : "התחבר",
        "sign up":"הרשמה",
        "address":'כתובת',
        "rooms":'חדרים',
        "baths":'מקלחות',
        "more details":'פרטים נוספים',
        "sqft":'שטח',
        "status":'מצב',
        "price":'מחיר',
        "both":"השכרה / מכירה",
        "rent":"השכרה",
        "sale":"מכירה",
        "minPrice":" החל מ",
        "maxPrice":" עד",
        "numRoom":"מספר חדרים",
        "numBath" : "מספר מקלחות",
        "city":"עיר",
        "search":"חיפוש",
        "images":'תמונות',
        "details":"פרטים",
        "purchase":"רכישה",
        "found": "נמצאו",
        "advancedSearch":"חיפוש מתקדם",
        "location":"מיקום",
        "cancel":"ביטול",
        "type": "סוג",
        "uploadDate":"תאריך העלאה",
        "house":"בית",
        "ranch":"חווה",
        "condo":"דירה",
        "land":"בית קרקע",
        "all":"הכל",
        "agentDetails" : "פרטי סוכן",
        "name" : "שם",
        "email": " E-mail",
        "phone" : "מס' טלפון"

    }
};