export const data = {
    "en" : {
        "apartments":"Apartments",
        "aboutUs":"About us",
        "signIn" : "Sign In",
        "signUp":"Sign Up",
        "address":'Address',
        "rooms":'Rooms',
        "baths":'Baths',
        "more details":'More Details',
        "sqft":'Sqft',
        "status":'Status',
        "price":'Price',
        "both":"Sale / Rent",
        "rent":"Rent",
        "sale":"Sale",
        "minPrice":"Min Price",
        "maxPrice":"Max Price",
        "numRoom":"Number of rooms",
        "numBath" : "Number of baths",
        "city":"City",
        "search":"Search",
        "images":'Images',
        "details":"Details",
        "purchase":"Purchase",
        "found" : "Found",
        "advancedSearch":"Advanced Search",
        "location":"Location",
        "cancel":"Cancel",
        "type" : "Type",
        "uploadDate":"Upload Date",
        "house":"House",
        "ranch":"Ranch",
        "condo":"Condo",
        "land":"land",
        "all":"All",
        "agentDetails" : "Agent Details",
        "name" : "Name",
        "email": " E-mail",
        "phone" : "Phone",
        "login" : "Log In",
        "password" : "PassWord",
        "erroLog" : "Incorrect E-mail or Password",
        "logOut" : "Log Out",
        "hello" : "Hello",
        "sale_status" : "Operation",
        "pending":"Pending",
        "approved" : "Approved",
        "denied" : "Denied",
        "removed" : "Removed",
        "id" : "Id",
        "view" : "View",
        "edit" : "Edit",
        "homePageHeader":"The Home of Home Search",
        "subSectionHome" : "Do you have a home you want to sell or rent? I will be happy to help",
        "statisticsHeader" : "Whats happening in Israel",
        "aboutUsText":"realEstate.com Is the leading real estate site in Israel that offers a board with a selection of apartments and houses for sale and rent, lots and more. For the avoidance of doubt, the copyright and property of the property belong to the property owners. It is hereby clarified that the Website constitutes a publicity platform for users / users and the Company is not responsible in any way for the third party services and property prices. The site may remove or edit any advertising on the site if it finds that this publication violates the Terms of Service. Use of the Website, for all its services, is solely your responsibility"
    },
    "he":{
        "apartments":"דירות",
        "aboutUs":"אודות",
        "signIn" : "התחבר",
        "signUp":"הרשמה",
        "address":'כתובת',
        "rooms":'חדרים',
        "baths":'מקלחות',
        "more details":'פרטים נוספים',
        "sqft":'שטח',
        "status":'מצב',
        "price":'מחיר',
        "both":"השכרה / מכירה",
        "rent":"השכרה",
        "sale":"מכירה",
        "minPrice":" החל מ",
        "maxPrice":" עד",
        "numRoom":"מספר חדרים",
        "numBath" : "מספר מקלחות",
        "city":"עיר",
        "search":"חיפוש",
        "images":'תמונות',
        "details":"פרטים",
        "purchase":"רכישה",
        "found": "נמצאו",
        "advancedSearch":"חיפוש מתקדם",
        "location":"מיקום",
        "cancel":"ביטול",
        "type": "סוג",
        "uploadDate":"תאריך העלאה",
        "house":"בית",
        "ranch":"חווה",
        "condo":"דירה",
        "land":"בית קרקע",
        "all":"הכל",
        "agentDetails" : "פרטי סוכן",
        "name" : "שם",
        "email": "דואר אלקטרוני",
        "phone" : "מס' טלפון",
        "login" : "התחבר",
        "password" : "סיסמה",
        "erroLog" : "שם משתמש או סיסמא שגוי",
        "logOut" : "יציאה",
        "hello" : "ברוך הבא",
        "sale_status" : "פעולה",
        "pending":"ממתין לאישור המנהל",
        "approved" : "אושר",
        "denied" : "נדחה",
        "removed" : "נמחק",
        "id" : "Id",
        "view" : "הצג",
        "edit" : "ערוך",
        "homePageHeader":"הבית לחיפוש בית",
        "subSectionHome" : "יש לכם בית שאתם רוצים למכור או להשכיר? אשמח לעזור",
        "statisticsHeader" : "מה קורה בישראל",
        "aboutUsText":"האתר הינו אתר הנדל״ן המוביל בישראל המציע לוח עם מבחר דירות ובתים למכירה ולהשכרה, מגרשים ועוד. \n" +
            "למען הסר ספק, זכויות היוצרים והקניין של הנכסים, שייכים לבעלי הדירות.\n" +
            "מובהר בזאת, כי האתר מהווה פלטפורמת פרסום לגולשים/משתמשים והחברה אינה אחראית בכל צורה שהיא לשירותי הצד השלישי ומחירי הנכסים. האתר רשא להסיר או לערוך כל פרסום באתר במידה וימצא כי פרסום זה מפר את תנאי התקנון.\n" +
            "השימוש באתר, על כל מגוון שירותיו הינו באחריותך בלבד"



    }
};

